title: Nick Glazer
author: Nick Glazer
avatar_url: https://nickglazer.github.io/nick-glazer-resume/nickg.jpg
email: nick@glazer.dev
description: >-
  I am a software developer.
baseurl: ""
url: "https://glazer.dev"
github_username: nickglazer
linkedin_username: nickglazerdev
show_excerpts: true
permalink: pretty
exclude: ['README.md']

header_pages:
  - about.md
  - resume.html

projects:
  - deathly-hallows-portrait-generator
  - threat-locator
  - med-map
  - car-inventory
  - povon-test-server
  - python-state-machine-framework
  - python-practice
  - meta-qpcpp

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-github-metadata
  - jekyll-octicons
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
